package cmd

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
	yaml "go.yaml.in/yaml/v3"

	"github.com/ul0gic/flightline/internal/config"
	"github.com/ul0gic/flightline/internal/state"
)

const yamlSchemaHeader = "# yaml-language-server: $schema=" + config.SchemaURL

func init() {
	cmd := &cobra.Command{
		Use:   "fetch <bundleId>",
		Short: "Fetch live App Store Connect state into a state.yaml",
		Long: `Pulls every L2 surface Flightline supports for the given bundleId and writes
the result as a Flightline state file. Default output is YAML with a
yaml-language-server schema directive prepended for editor autocomplete.

Surfaces not yet implemented (see QA-009) appear absent from the output;
the diff engine treats absence as "not managed" so Flightline leaves them
alone on subsequent applies.

Examples:
  flightline fetch com.under5.passdmv > state.yaml
  flightline fetch com.under5.passdmv -o state.yaml --version 1.0.1
  flightline fetch com.under5.passdmv --output json | jq '.spec.version'`,
		Args: cobra.ExactArgs(1),
		RunE: runFetch,
	}
	cmd.Flags().StringP("output-file", "o", "", "write to file instead of stdout (YAML only)")
	cmd.Flags().String("version", "", "App Store version string (default: latest editable)")
	cmd.Flags().String("platform", "IOS", "Apple platform: IOS | MAC_OS | TV_OS | VISION_OS")
	rootCmd.AddCommand(cmd)
}

func runFetch(cmd *cobra.Command, args []string) error {
	bundleID := args[0]
	c, err := newClient()
	if err != nil {
		return err
	}
	version, _ := cmd.Flags().GetString("version")
	platform, _ := cmd.Flags().GetString("platform")

	st, err := state.Fetch(cmd.Context(), c, bundleID, state.FetchOpts{
		Version: version, Platform: platform,
	})
	if err != nil {
		return err
	}

	mode := outputMode()
	switch mode {
	case "json":
		return Render(st, "json")
	case "table":
		// A state file has no sensible table form; fall back to JSON.
		fmt.Fprintln(os.Stderr, "flightline: fetch has no table view; emitting JSON. Pass --output yaml or omit -o for YAML.")
		return Render(st, "json")
	case "yaml", "":
		return writeStateYAML(cmd, st)
	default:
		return fmt.Errorf("fetch: unknown --output %q (expected yaml | json)", mode)
	}
}

func writeStateYAML(cmd *cobra.Command, st *config.State) error {
	target, _ := cmd.Flags().GetString("output-file")

	var buf strings.Builder
	if err := encodeYAMLForTest(&buf, st); err != nil {
		return err
	}

	out := buf.String()
	if target == "" {
		_, err := os.Stdout.WriteString(out)
		return err
	}
	if err := os.WriteFile(target, []byte(out), 0o600); err != nil {
		return fmt.Errorf("fetch: write %s: %w", target, err)
	}
	fmt.Fprintf(os.Stderr, "flightline: wrote %s (%d bytes)\n", target, len(out))
	return nil
}

func encodeYAMLForTest(w io.Writer, st *config.State) error {
	if _, err := io.WriteString(w, yamlSchemaHeader); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n#\n# Generated by `flightline fetch`: edit, then `flightline plan` to preview\n# the diff against live ASC, and `flightline apply --confirm` to write.\n\n"); err != nil {
		return err
	}
	enc := yaml.NewEncoder(w)
	enc.SetIndent(2)
	if err := enc.Encode(st); err != nil {
		return fmt.Errorf("fetch: encode yaml: %w", err)
	}
	if err := enc.Close(); err != nil {
		return fmt.Errorf("fetch: close yaml encoder: %w", err)
	}
	return nil
}
