// Command gen-docs regenerates the mechanical reference docs from source so they cannot drift.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/ul0gic/flightline/internal/cmd"
	"github.com/ul0gic/flightline/internal/lint"
)

const banner = "<!-- generated by gen-docs; do not edit, run make gen-docs -->"

func main() {
	if err := run(os.Args); err != nil {
		fmt.Fprintf(os.Stderr, "gen-docs: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	outDir := "docs/reference"
	if len(args) > 1 {
		outDir = args[1]
	}

	files := map[string]string{
		"cli.md":             renderCLI(cmd.Root()),
		"preflight-rules.md": renderRules(lint.All()),
	}
	for name, content := range files {
		path := filepath.Join(outDir, name)
		err := os.WriteFile(path, []byte(content), 0o644) // #nosec G306 G703 -- committed reference docs are world-readable; outDir is a trusted build-time argument
		if err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}
	return nil
}

func renderCLI(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString(banner + "\n\n# CLI reference\n\n")
	b.WriteString("Commands, arguments, flags and examples below are generated from the CLI definitions. Run `flightline <command> --help` to check your installed version. Placeholders such as `<bundleId>` must be replaced with your own values.\n\n")
	b.WriteString("## Global options\n\nThese options are inherited by subcommands unless overridden.\n\n")
	renderFlags(&b, root.PersistentFlags())
	b.WriteString("## Command groups\n\n| Group | Summary |\n|---|---|\n")
	for _, c := range root.Commands() {
		if skipCommand(c) {
			continue
		}
		fmt.Fprintf(&b, "| [`%s`](#%s) | %s |\n", c.Name(), c.Name(), tableText(c.Short))
	}
	b.WriteString("\n")
	for _, c := range root.Commands() {
		if !skipCommand(c) {
			renderCommand(&b, c, 2)
		}
	}
	return b.String()
}

func skipCommand(c *cobra.Command) bool {
	return c.Hidden || c.Name() == "help" || c.Name() == "completion"
}
func tableText(s string) string {
	return strings.NewReplacer("|", "&#124;", "\n", " ", "\r", "").Replace(s)
}
func renderFlags(b *strings.Builder, flags *pflag.FlagSet) {
	var rows strings.Builder
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name += ", -" + f.Shorthand
		}
		required := "No"
		if len(f.Annotations[cobra.BashCompOneRequiredFlag]) > 0 {
			required = "Yes"
		}
		value := f.DefValue
		if value == "" {
			value = "(empty)"
		}
		fmt.Fprintf(&rows, "| `%s` | `%s` | %s | `%s` | %s |\n", name, f.Value.Type(), required, tableText(value), tableText(f.Usage))
	})
	if rows.Len() == 0 {
		return
	}
	b.WriteString("| Flag | Type | Required | Default | Description |\n|---|---|---|---|---|\n" + rows.String() + "\n")
}
func renderCommand(b *strings.Builder, c *cobra.Command, depth int) {
	flags := c.LocalFlags()
	title := strings.TrimPrefix(c.CommandPath(), c.Root().Name()+" ")
	fmt.Fprintf(b, "%s `%s`\n\n%s\n\n", strings.Repeat("#", depth), title, groupBlurb(c))
	fmt.Fprintf(b, "**Usage**\n\n```text\n%s\n```\n\n", c.UseLine())
	if c.Example != "" {
		fmt.Fprintf(b, "**Examples**\n\n```bash\n%s\n```\n\n", strings.TrimSpace(c.Example))
	}
	// Local flags include persistent flags defined on this command; inherited ones
	// are documented on their ancestor rather than repeated for every leaf.
	renderFlags(b, flags)
	if c.Deprecated != "" {
		fmt.Fprintf(b, "Deprecated: %s\n\n", c.Deprecated)
	}
	for _, child := range c.Commands() {
		if !skipCommand(child) {
			renderCommand(b, child, 3)
		}
	}
}

// groupBlurb prefers the cobra Long help collapsed to one paragraph, falling back to Short.
func groupBlurb(c *cobra.Command) string {
	text := strings.TrimSpace(c.Long)
	if text == "" {
		return c.Short
	}
	return strings.Join(strings.Fields(text), " ")
}

func renderRules(rules []lint.Rule) string {
	sort.Slice(rules, func(i, j int) bool { return rules[i].ID() < rules[j].ID() })

	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n\n# Preflight rules\n\n")
	b.WriteString("Flightline checks supported schema, consistency and release-readiness requirements. Passing these checks does not guarantee App Review approval. The `ruleId` is a stable JSON contract; renaming one is a breaking change.\n\n")
	b.WriteString("Two commands run the rules: `flightline lint <state.yaml>` (offline) and `flightline preflight <bundleId> --version <v>` (live). Both emit a stable JSON contract via `--output json`.\n\n")

	b.WriteString("## Severity and exit codes\n\n")
	b.WriteString("| Severity | Meaning | Exit code |\n")
	b.WriteString("|----------|---------|-----------|\n")
	b.WriteString("| `error` | A validation or readiness issue. The command exits nonzero. | `1` |\n")
	b.WriteString("| `warning` | A finding to review. Warnings produce a nonzero exit when no errors are present. | `2` (when no errors present) |\n")
	b.WriteString("| `info` | Additional context. Info-only results exit successfully. | `0` |\n\n")
	b.WriteString("When both errors and warnings are present, exit code is `1`.\n\n")

	b.WriteString("## Quick index\n\n")
	b.WriteString("| Rule ID | Mode | Severity |\n")
	b.WriteString("|---------|------|----------|\n")
	for _, r := range rules {
		fmt.Fprintf(&b, "| [`%s`](#%s) | %s | %s |\n", r.ID(), ruleAnchor(r.ID()), modeString(r.Mode()), severityString(r.Severity()))
	}
	b.WriteString("\nRules are sorted alphabetically by ID, the same order the runner executes them in.\n\n")

	b.WriteString("## Rule reference\n\n")
	for _, r := range rules {
		fmt.Fprintf(&b, "### `%s`\n\n", r.ID())
		fmt.Fprintf(&b, "- **Mode:** %s\n", modeString(r.Mode()))
		fmt.Fprintf(&b, "- **Severity:** %s\n\n", severityString(r.Severity()))
		fmt.Fprintf(&b, "%s\n\n", r.Doc())
	}
	return b.String()
}

// ruleAnchor builds the GitHub-style heading slug for a rule ID; backticks drop and dots are removed.
func ruleAnchor(id string) string {
	return strings.ReplaceAll(id, ".", "")
}

func modeString(m lint.Mode) string {
	switch m {
	case lint.ModeOffline:
		return "Offline"
	case lint.ModeLive:
		return "Live"
	case lint.ModeBoth:
		return "Both"
	default:
		return fmt.Sprintf("mode(%d)", int(m))
	}
}

func severityString(s lint.Severity) string {
	return strings.ToUpper(s.String()[:1]) + s.String()[1:]
}
