// Command gen-docs regenerates the mechanical reference docs from source so they cannot drift.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/ul0gic/flightline/internal/cmd"
	"github.com/ul0gic/flightline/internal/lint"
)

const banner = "<!-- generated by gen-docs; do not edit, run make gen-docs -->"

func main() {
	if err := run(os.Args); err != nil {
		fmt.Fprintf(os.Stderr, "gen-docs: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	outDir := "docs/reference"
	if len(args) > 1 {
		outDir = args[1]
	}

	files := map[string]string{
		"cli.md":             renderCLI(cmd.Root()),
		"preflight-rules.md": renderRules(lint.All()),
	}
	for name, content := range files {
		path := filepath.Join(outDir, name)
		//nolint:gosec // committed reference docs are world-readable by design, not secrets
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}
	return nil
}

func renderCLI(root *cobra.Command) string {
	groups := make([]*cobra.Command, 0, len(root.Commands()))
	for _, c := range root.Commands() {
		if c.Hidden || c.Name() == "help" || c.Name() == "completion" {
			continue
		}
		groups = append(groups, c)
	}
	sort.Slice(groups, func(i, j int) bool { return groups[i].Name() < groups[j].Name() })

	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n\n# CLI reference\n\n")
	b.WriteString("This is a command-group index. The source of truth for flags, arguments, and defaults is the built-in help: run `flightline <group> --help` (or `flightline <group> <subcommand> --help`). The help text is generated from the code, so it never drifts. This page deliberately does not duplicate flags.\n\n")
	b.WriteString("```bash\n")
	b.WriteString("flightline --help              # top-level command tree\n")
	b.WriteString("flightline <group> --help      # a command group and its subcommands\n")
	b.WriteString("```\n\n")
	b.WriteString("Every command supports `--output table` (default) and `--output json`. JSON is a stable contract for pipes and LLM consumers.\n\n")
	b.WriteString("| Group | Summary |\n")
	b.WriteString("|-------|---------|\n")
	for _, c := range groups {
		fmt.Fprintf(&b, "| [`%s`](#%s) | %s |\n", c.Name(), c.Name(), c.Short)
	}
	b.WriteString("\n")
	for _, c := range groups {
		fmt.Fprintf(&b, "## `%s`\n\n", c.Name())
		fmt.Fprintf(&b, "%s\n\n", groupBlurb(c))
		fmt.Fprintf(&b, "Flags, arguments, and defaults: `flightline %s --help`.\n\n", c.Name())
	}
	return b.String()
}

// groupBlurb prefers the cobra Long help collapsed to one paragraph, falling back to Short.
func groupBlurb(c *cobra.Command) string {
	text := strings.TrimSpace(c.Long)
	if text == "" {
		return c.Short
	}
	return strings.Join(strings.Fields(text), " ")
}

func renderRules(rules []lint.Rule) string {
	sort.Slice(rules, func(i, j int) bool { return rules[i].ID() < rules[j].ID() })

	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n\n# Preflight rules\n\n")
	b.WriteString("Flightline's L3 layer catches the clerical mistakes that cause Apple to reject a release. Each rule encodes a real rejection pattern. The `ruleId` is a stable JSON contract; renaming one is a breaking change.\n\n")
	b.WriteString("Two commands run the rules: `flightline lint <state.yaml>` (offline) and `flightline preflight <bundleId> --version <v>` (live). Both emit a stable JSON contract via `--output json`.\n\n")

	b.WriteString("## Severity and exit codes\n\n")
	b.WriteString("| Severity | Meaning | Exit code |\n")
	b.WriteString("|----------|---------|-----------|\n")
	b.WriteString("| `error` | Known rejection cause or structural problem that blocks `apply`. Preflight exits non-zero. | `1` |\n")
	b.WriteString("| `warning` | Worth fixing; Apple is unlikely to hard-reject for it. | `2` (when no errors present) |\n")
	b.WriteString("| `info` | A reminder or hint. Never gates submission. | `0` |\n\n")
	b.WriteString("When both errors and warnings are present, exit code is `1`.\n\n")

	b.WriteString("## Quick index\n\n")
	b.WriteString("| Rule ID | Mode | Severity |\n")
	b.WriteString("|---------|------|----------|\n")
	for _, r := range rules {
		fmt.Fprintf(&b, "| [`%s`](#%s) | %s | %s |\n", r.ID(), ruleAnchor(r.ID()), modeString(r.Mode()), severityString(r.Severity()))
	}
	b.WriteString("\nRules are sorted alphabetically by ID, the same order the runner executes them in.\n\n")

	b.WriteString("## Rule reference\n\n")
	for _, r := range rules {
		fmt.Fprintf(&b, "### `%s`\n\n", r.ID())
		fmt.Fprintf(&b, "- **Mode:** %s\n", modeString(r.Mode()))
		fmt.Fprintf(&b, "- **Severity:** %s\n\n", severityString(r.Severity()))
		fmt.Fprintf(&b, "%s\n\n", r.Doc())
	}
	return b.String()
}

// ruleAnchor builds the GitHub-style heading slug for a rule ID; backticks drop and dots are removed.
func ruleAnchor(id string) string {
	return strings.ReplaceAll(id, ".", "")
}

func modeString(m lint.Mode) string {
	switch m {
	case lint.ModeOffline:
		return "Offline"
	case lint.ModeLive:
		return "Live"
	case lint.ModeBoth:
		return "Both"
	default:
		return fmt.Sprintf("mode(%d)", int(m))
	}
}

func severityString(s lint.Severity) string {
	return strings.ToUpper(s.String()[:1]) + s.String()[1:]
}
